apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp-deployment
  labels:
    app: frontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata:
      labels:
        app: frontendapp
    spec:
      containers:
      - name: frontendapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapp-service
spec:
  selector:
   app: frontendapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000